name: CPP formatting check with clang-format
description: A GitHub Action to check C++ code formatting using clang-format.
author: jaytakahashii

inputs:
  path:
    description: "Directory to check for C++ files"
    required: true
    default: "src"
  style:
    description: "Clang format style (e.g., Google, LLVM, etc.)"
    required: false
    default: "Google"

runs:
  using: "docker"
  image: "docker://ghcr.io/jaytakahashii/clang-format-check:latest"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.style }}

branding:
  icon: "check-circle"
  color: "purple"
