name: Example Clang Format Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CPP formatting check with clang-format
        uses: jaytakahashii/clang-format-check@v1.0.2
        with:
          path: "src"
          style: "Google"
