name: Example Clang Format Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Clang Format Check
        uses: jtakahashii/clang-format-check@v1
        with:
          path: "src"
          style: "Google"
