name: Example Clang Format Workflow

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Clang Format Check
        uses: jaytakahashii/clang-format-check@v2
        with:
          path: "src"
          style: "Google"
